#!/system/xbin/busybox sh

# enable sd-ext
	if [ -e /dev/block/mmcblk0p2 ] ; then
		insmod /system/lib/modules/ext2.ko
		insmod /system/lib/modules/jbd.ko
		insmod /system/lib/modules/ext3.ko
		mount /dev/block/mmcblk0p2 /sd-ext
		if [ $? -eq 0 ] ; then
			mkdir /sd-ext/app ; chmod 777 /sd-ext/app
			[[ -d /data/app ]] && cp -a /data/app/* /sd-ext/app/
			[[ -d /data/app ]] && rm -R /data/app
			ln -s /sd-ext/app /data/app
		fi
	fi

