#!/system/bin/sh

# DarkTremor A2SD seems to think something this might help.
# It's worth a shot.
parts=$(fdisk -l /dev/block/mmcblk0)
for i in 1 2 3 ; do
    mmcblk=/dev/block/mmcblk0p$i
    if echo $parts | grep -q $mmcblk ; then
	[ -b $mmcblk ] || sleep 3
	[ -b $mmcblk ] || mknod $mmcblk 179 $i
    fi
done

