#!/system/bin/sh

# Forbid Link2SD from monkeying around on its own
if [ -f /system/etc/11link2sd ] ; then
	busybox mount -o remount,rw /system
	rm /system/etc/11link2sd
	sync
	busybox mount -o remount,ro /system
fi

# Don't do anything else unless link2sd is selected
[ -f /system/etc/sdext/link2sd ] || exit

if [ "$SD_EXT_DIRECTORY" = "" ];
then
        SD_EXT_DIRECTORY=/sd-ext
fi
if [ "`egrep -q $SD_EXT_DIRECTORY /proc/mounts;echo $?`" != "0" ];
then
        echo "$SD_EXT_DIRECTORY not mounted.. skipping link2sd"
        exit
fi

for dir in $SD_EXT_DIRECTORY/link2sd /data/sdext2 ; do
	[ -d $dir/ ] || install -m 771 -o 1000 -g 1000 -d $dir
	[ -d $dir/ ] || exit 1
done

mount -o bind $SD_EXT_DIRECTORY/link2sd/ /data/sdext2
